#define HAS_ERRORS 1
#define FATAL_USAGE -1
#define FATAL_CANTREAD -2
#define FATAL_CANTWRITE -3

#define COMPERR_SYNTAX 			1

#define COMPERR_MISSINGCHAR      2
#define COMPERR_MISSINGKEYWORD	3
#define COMPERR_MISSINGINDEX 		4

#define COMPERR_EOLEXPECTED      5
#define COMPERR_UNEXPECTEDEOL    6
#define COMPERR_EOSEXPECTED      7
#define COMPERR_UNEXPECTEDEOS    8

#define COMPERR_VAREXPECTED 9
#define COMPERR_PORTEXPECTED 10
#define COMPERR_BITPORTEXPECTED 11
#define COMPERR_CONSTEXPECTED 12
#define COMPERR_GOTOGOSUBEXPECTED 13
#define COMPERR_NEXTWITHOUTFOR 14


#define COMPERR_UNDEFINEDSYMBOL  15
#define COMPERR_INVALIDSYMBOL    16
#define COMPERR_SYMBOLREDEFINED 17
#define COMPERR_UNDEFINEDLABEL  18
#define COMPERR_LABELREDEFINED  19

#define COMPERR_OUTOFRANGE       20
#define COMPERR_PROGRAMTOOLONG   21
#define COMPERR_SYSPROGRAMTOOLONG 22

#define COMPERR_INVALIDFUNCTIONCALL 23
#define COMPERR_FILENOTFOUND 24
#define COMPERR_INVALIDFILEFORMAT 25

#define COMPERR_SYNTAXERROR 26
#define COMPERR_NOMAILSLOT 27
